{{- if .Values.databases }}
{{- range .Values.databases }}
{{- if .enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ .name }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  cluster:
    name: {{ .cluster }}
  name: {{ .name }}
  {{- with .owner }}
  owner: {{ . }}
  {{- end }}
  {{- with .ensure }}
  ensure: {{ . }}
  {{- end }}
  {{- with .template }}
  template: {{ . }}
  {{- end }}
  {{- with .encoding }}
  encoding: {{ . }}
  {{- end }}
  {{- with .locale }}
  locale: {{ . }}
  {{- end }}
  {{- with .localeProvider }}
  localeProvider: {{ . }}
  {{- end }}
  {{- with .localeCollate }}
  localeCollate: {{ . }}
  {{- end }}
  {{- with .localeCType }}
  localeCType: {{ . }}
  {{- end }}
  {{- with .icuLocale }}
  icuLocale: {{ . }}
  {{- end }}
  {{- with .icuRules }}
  icuRules: {{ . }}
  {{- end }}
  {{- with .builtinLocale }}
  builtinLocale: {{ . }}
  {{- end }}
  {{- with .collationVersion }}
  collationVersion: {{ . }}
  {{- end }}
  {{- if hasKey . "isTemplate" }}
  isTemplate: {{ .isTemplate }}
  {{- end }}
  {{- if hasKey . "allowConnections" }}
  allowConnections: {{ .allowConnections }}
  {{- end }}
  {{- if hasKey . "connectionLimit" }}
  connectionLimit: {{ .connectionLimit }}
  {{- end }}
  {{- with .tablespace }}
  tablespace: {{ . }}
  {{- end }}
  {{- with .databaseReclaimPolicy }}
  databaseReclaimPolicy: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}