{{- if .Values.serviceMonitor.enabled }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "qs-pgbouncer.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "qs-pgbouncer.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "qs-pgbouncer.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    {{- with .Values.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    path: {{ .Values.serviceMonitor.path | default "/metrics" }}
    {{- with .Values.serviceMonitor.honorLabels }}
    honorLabels: {{ . }}
    {{- end }}
    {{- with .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- else }}
{{- if .Values.serviceMonitor.enabled }}
{{- fail "ServiceMonitor CRD (monitoring.coreos.com/v1) is not available. Please install Prometheus Operator first." }}
{{- end }}
{{- end }}
{{- end }}
