apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "quick-start.fullname" . }}-secret-creator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quick-start.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "quick-start.fullname" . }}-secret-creator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quick-start.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "quick-start.fullname" . }}-secret-creator
subjects:
- kind: ServiceAccount
  name: {{ include "quick-start.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
