stakater/reloader
dexidp/dex
proxy-docker/qdrant/qdrant
proxy-docker/openfga/openfga
proxy-ghcr/cloudnative-pg/cloudnative-pg
proxy-ghcr/cloudnative-pg/postgresql
brancz/kube-rbac-proxy
proxy-ghcr/zitadel/zitadel
prometheuscommunity/postgres-exporter
proxy-ghcr/zitadel/zitadel
docker.io/apteno/alpine-jq
docker.io/curlimages/curl
ghcr.io/zitadel/zitadel
kserve/kserve-controller
temporalio/admin-tools
temporalio/server
temporalio/ui
